# Generated by Django 2.2.5 on 2019-12-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='space_quota',
            field=models.IntegerField(default=50),
        ),
    ]
